# Vigia Render-Compatible Docker Compose
# Simplified deployment for cloud platforms like Render
# Use this for development/testing of Render deployment locally

version: '3.8'

services:
  # Main Vigia service (single container)
  vigia-web:
    build:
      context: .
      dockerfile: Dockerfile.render
    container_name: vigia-web
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      # Core settings
      - PORT=${PORT:-8000}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - PYTHONPATH=/app
      
      # Medical settings
      - MEDICAL_COMPLIANCE_LEVEL=${MEDICAL_COMPLIANCE_LEVEL:-basic}
      - PHI_PROTECTION_ENABLED=${PHI_PROTECTION_ENABLED:-true}
      
      # External services (optional)
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      
      # API keys (optional)
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_FROM=${TWILIO_WHATSAPP_FROM}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      
      # Webhook settings
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_ENABLED=${WEBHOOK_ENABLED:-true}
      
      # Monitoring (optional)
      - AGENTOPS_API_KEY=${AGENTOPS_API_KEY}
      
    volumes:
      # Only essential volumes for development
      - ./logs:/app/logs
      - ./data/output:/app/data/output
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: false  # Allow writes to /app/tmp and /app/logs
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/tmp:noexec,nosuid,size=50m

  # Optional Redis for development (not needed on Render with external Redis)
  redis:
    image: redis:7-alpine
    container_name: vigia-redis-dev
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - development
      - with-redis

volumes:
  redis_data:

networks:
  default:
    name: vigia-render