services:
  # WhatsApp Bot Service
  - type: web
    name: vigia-whatsapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_whatsapp.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  # Webhook API Service
  - type: web
    name: vigia-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_webhook.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true