name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

env:
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create .env file
      run: |
        cat > .env << EOF
        TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_WHATSAPP_FROM=${{ secrets.TWILIO_WHATSAPP_FROM }}
        ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
        SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}
        SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        REDIS_URL=redis://redis:6379
        ENVIRONMENT=staging
        RATE_LIMIT_ENABLED=true
        RATE_LIMIT_PER_MINUTE=30
        EOF
    
    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.staging.yml up -d
    
    - name: Wait for services to be healthy
      run: |
        echo "Waiting for services to start..."
        sleep 30
        docker-compose -f docker-compose.staging.yml ps
    
    - name: Run E2E validation
      run: |
        docker-compose -f docker-compose.staging.yml exec -T vigia python scripts/e2e_validation.py
    
    - name: Show logs on failure
      if: failure()
      run: |
        docker-compose -f docker-compose.staging.yml logs