name: Claude Code Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  claude-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            Please analyze this medical system codebase focusing on:
            - Security and HIPAA compliance
            - Medical data handling and PHI protection
            - Code quality and architecture
            - Potential vulnerabilities or issues
            
            Pay special attention to:
            - PHI tokenization implementation
            - Database separation architecture
            - Medical AI integration
            - Audit trail completeness
